title:            ChelebNet
description:      .zZ
url:              https://cheleb.net
permalink:        pretty
timezone:         Europe/Oslo
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
