title:            ChelebNet
description:      .zZ
url:              https://vhffm.github.io
domain:           vhffm.github.io
#baseurl:          _site/
permalink:        pretty
timezone:         Europe/Oslo
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
